export const data = {
  dates: {
    maximum: "2023-02-23",
    minimum: "2023-01-06",
  },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/q2fY4kMXKoGv4CQf310MCxpXlRI.jpg",
      genre_ids: [878, 27, 35],
      id: 536554,
      original_language: "en",
      original_title: "M3GAN",
      overview:
        "교통사고로 부모를 잃고 혼자가 된 소녀 ‘케이디’. 로봇 엔지니어이자, ‘케이디’의 보호자가 된 ‘젬마’는 ‘케이디’를 안전하게 지켜야 하는 프로그램이 입력된 AI 로봇 ‘메간’을 선물한다. 메간은 언제나 ‘케이디’의 곁을 지켜주며 함께 웃고, 힘들 땐 위로해주는 둘도 없는 친구가 된다. 어느 날, ‘케이디’가 위험에 처하자 ‘메간’은 예측할 수 없는 방향으로 업그레이드되며 감당할 수 없는 일들이 벌어지는데…",
      popularity: 1572.141,
      poster_path: "/v0TtgXaZZ6NeDxKackgQK9byEDL.jpg",
      release_date: "2023-01-25",
      title: "메간",
      video: false,
      vote_average: 7.5,
      vote_count: 1612,
    },
    {
      adult: false,
      backdrop_path: "/tlZBdyjh12tBJH4EW047hEigShA.jpg",
      genre_ids: [878, 12, 35],
      id: 640146,
      original_language: "en",
      original_title: "Ant-Man and the Wasp: Quantumania",
      overview:
        "슈퍼히어로 파트너인 스캇 랭과 호프 반 다인, 호프의 부모 재닛 반 다인과 행크 핌, 그리고 스캇의 딸 캐시 랭까지 미지의 양자 영역 세계 속에 빠져버린 앤트맨 패밀리. 그 곳에서 새로운 존재들과 무한한 우주를 다스리는 정복자 캉을 만나며, 그 누구도 예상 못 한 모든 것의 한계를 뛰어넘는 모험을 시작하게 되는데…",
      popularity: 1349.905,
      poster_path: "/cw6jBnTauNmEEIIXcoNEyoQItG7.jpg",
      release_date: "2023-02-15",
      title: "앤트맨과 와스프: 퀀텀매니아",
      video: false,
      vote_average: 6.6,
      vote_count: 223,
    },
    {
      adult: false,
      backdrop_path: "/vLPSvAt1CnfmDCeqG3zkFh0s6S4.jpg",
      genre_ids: [10752, 28],
      id: 542196,
      original_language: "en",
      original_title: "Wolf Hound",
      overview:
        "연합군의 전투비행단이 독일 전투기에 급습을 당한다. 홀로 적진에 추락한 파일럿은 독일군의 추격을 받고 런던 폭격의 일급 작전인 코드네임 ‘울프 하운드’를 알게 된다. 독일군 기지에 잠입해 포로로 잡힌 동료를 탈출시키고 폭격을 막기 위해 함께 지상전과 공중전을 벌이는데…",
      popularity: 465.13,
      poster_path: "/uSQq9TExOdZc5PCyxBuqaVuALZ7.jpg",
      release_date: "2023-02-09",
      title: "울프 하운드",
      video: false,
      vote_average: 6.6,
      vote_count: 70,
    },
    {
      adult: false,
      backdrop_path: "/vXjpwkXPirBmgdEpIknfN8ziDD.jpg",
      genre_ids: [16, 12, 14, 35],
      id: 947938,
      original_language: "ru",
      original_title: "Мальчик-дельфин",
      overview:
        "돌고래야, 사람이야?! 정체를 알 수 없는 녀석이 온다! 바다 속 돌고래와 함께 자란 소년 ‘보이’ 어느 날 친엄마의 존재를 알게 된 ‘보이’는 자신의 뿌리를 궁금해하기 시작하고 … 혼란스러운 상황 속 ‘보이’는 악당 ‘옥토퍼스’로 인해 엄마 돌고래 ‘나나’를 잃고 해안가로 떠밀려간다. 평생을 자신이 돌고래인 줄 알고 살던 ‘보이’는 해안가에 사는 ‘머버리드 선장’의 도움으로 친엄마를 찾아내기로 결심하는데 … 2023년, 올겨울 유일무이 오션 어드벤처가 온다!",
      popularity: 573.165,
      poster_path: "/Aif2IsFGCur5KoXnjkXyAhishMj.jpg",
      release_date: "2023-01-25",
      title: "돌핀보이",
      video: false,
      vote_average: 5.9,
      vote_count: 26,
    },
    {
      adult: false,
      backdrop_path: "/gwRMwljwHoNCyyJVgMA2XC4qPUU.jpg",
      genre_ids: [18, 35],
      id: 615777,
      original_language: "en",
      original_title: "Babylon",
      overview:
        "황홀하면서도 위태로운 고대 도시 바빌론에 비유되는 할리우드에서 전성기를 누리고 있는 당대 최고의 스타 잭 콘래드.  누구나 잭과 같은 성공을 꿈꾸지만 아무나 이룰 수 없던 그 때, 화려한 데뷔를 위해 당차게 야망을 좇는 넬리 라로이와 열정적인 청년 매니 토레스가 영화 같은 삶을 꿈꾸며 할리우드에 입성한다. 하지만 할리우드에서는 기존 영화 산업의 틀을 깬 새로운 변화가 시작되고 그 격변의 한가운데에서 잭과 넬리, 그리고 매니는 살아남아 각자의 꿈을 이루기 위해 고군분투하는데...",
      popularity: 485.219,
      poster_path: "/5Wnt03vRoKphp1ADWgHKus20vLX.jpg",
      release_date: "2023-02-01",
      title: "바빌론",
      video: false,
      vote_average: 7.6,
      vote_count: 1044,
    },
    {
      adult: false,
      backdrop_path: "/rodjjIJ8oh9nuBp86PhojcYHTEN.jpg",
      genre_ids: [28, 9648, 53, 80],
      id: 740952,
      original_language: "en",
      original_title: "Savage Salvation",
      overview:
        "마약 중독을 이겨내고 새로운 삶을 살길 원하는 ‘존’(잭 휴스턴)과 ‘루비’(윌라 피츠제럴드). 둘은 결혼을 약속하고 루비의 형부 ‘피터'(존 말코비치)는 존을 가족으로 따뜻하게 맞아준다. 과거의 죄를 씻고 구원을 바라는 루비의 세례를 앞둔 날, 약물 과다 투여로 죽어 있는 루비를 발견한 존은 절망에 빠지고 그녀를 죽음에 이르게 한 마약 공급책을 끝장내기 위해 복수에 나선다. 마을의 ‘마이크’ 보안관(로버트 드 니로)은 존의 폭주를 막기 위해 뒤를 쫓는데...",
      popularity: 293.949,
      poster_path: "/lvaksAQd82i4fJqr16664GcGUTf.jpg",
      release_date: "2023-01-26",
      title: "새비지 맨",
      video: false,
      vote_average: 6.6,
      vote_count: 103,
    },
    {
      adult: false,
      backdrop_path: "/6YRQ8l93ZEs6x4rZojWoHIWdguK.jpg",
      genre_ids: [28, 80],
      id: 1024546,
      original_language: "en",
      original_title: "Detective Knight: Rogue",
      overview:
        "미국 전역에서 강도 사건이 발생하고 현장에 나간 동료 형사 ‘피츠제럴드’가 목숨을 잃는다. 전직 스포츠 선수들이 범인이라는 단서를 찾은 ‘나이트’는 그들의 배후에 불법 도박업자 ‘위나’가 있다는 사실을 알게 되고, 복수와 정의를 위해 그들의 본거지인 뉴욕으로 향한 ‘나이트’는 과연 정의를 사수하고 복수를 실현할 수 있을까",
      popularity: 274.705,
      poster_path: "/7TxWlHkz5Guc9DCYo7ruVvnskDk.jpg",
      release_date: "2023-02-09",
      title: "디텍티브 나이트: 가면의 밤",
      video: false,
      vote_average: 6.7,
      vote_count: 74,
    },
    {
      adult: false,
      backdrop_path: "/59U5B10vsmVbgcCXzsFrzfG6SRb.jpg",
      genre_ids: [35, 10751, 10402],
      id: 830784,
      original_language: "en",
      original_title: "Lyle, Lyle, Crocodile",
      overview:
        "쇼맨 헥터(하비에르 바르뎀)는 어느 날 노래하는 악어 라일(숀 멘데스)을 발견하게 되고, 돈과 명예를 얻게 될 성공적인 무대를 꿈꾼다. 그러나 무대공포증에 있던 라일로 인해 무대는 실패하고 헥터는 라일을 홀로 도심에 남기고 떠난다.​  한편, 뉴욕에 이사 온 프림 가족은 매일 밤 의문의 노랫소리로 신기한 경험을 하게 되고, 그 놀라운 정체와 마주하게 되면서 인생이 바뀌게 되는데…",
      popularity: 274.152,
      poster_path: "/aWr7F5vK8LIY31sqQgINobBjBBK.jpg",
      release_date: "2023-01-18",
      title: "라일 라일 크로커다일",
      video: false,
      vote_average: 7.6,
      vote_count: 336,
    },
    {
      adult: false,
      backdrop_path: "/tIX6j3NzadlwGcJ52nuWdmtOQkg.jpg",
      genre_ids: [27, 53, 9648],
      id: 717728,
      original_language: "en",
      original_title: "Jeepers Creepers: Reborn",
      overview:
        "무시무시한 살인마 ‘크리퍼’의 존재에 푹 빠져 있는 호러 마니아 ‘체이스’와 그의 여자친구 ‘레인’. 그들은 마을에서 열리는 호러 마니아들의 축제, 호러 하운드 페스티벌에 참석한다. 순간 계속해서 떠오르는 정체 모를 기억과 소름 돋는 느낌에 레인은 혼란스러움을 느끼지만, 페스티벌 속 호러 이벤트에 당첨되어 신난 체이스를 따라 호러 저택 탐험을 떠난다. 한껏 고대하던 저택 탐험을 하게 된 설렘도 잠시, 무언가가 레인을 덮치고 체이스와 탐험 일행들은 피 비린내 나는 저택에 갇히게 되는데... 공포를 쫓던 호러 매니아들, 진짜 공포 ‘크리퍼’에게 쫓기다!",
      popularity: 269.082,
      poster_path: "/yt0lsyn7ortWByXrHRScEmSisvO.jpg",
      release_date: "2023-02-22",
      title: "지퍼스 크리퍼스: 리본",
      video: false,
      vote_average: 5.8,
      vote_count: 643,
    },
    {
      adult: false,
      backdrop_path: "/vmDa8HijINCAFYKqsMz0YM3sVyE.jpg",
      genre_ids: [28, 80, 53],
      id: 747803,
      original_language: "en",
      original_title: "One Way",
      overview:
        "죽여라! 도망쳐라! 살고 싶다면! 돌아갈 수 없는 편도행 버스 안에서 벌어지는 숨막히는 긴장감!  마약 조직의 보스 '빅'의 돈과 마약을 훔쳐 달아난 '프레디'는 야간 버스에 탑승해 도망친다. '빅'의 눈을 피해 도망갈 곳을 찾는 '프레디'는 친구인 '제이제이'와 아버지에게 전화를 걸며 도망칠 방법을 찾는다. 한편, 버스 안에는 집을 가출한 '레이첼'이 함께 탑승해 '프레디'에게 관심을 가지는데... 버스에서 내릴 수 없다면 목숨을 걸고 도망가야 한다. 과연, '프레디'는 무사히 버스에서 내려 가족을 만날 수 있을까?",
      popularity: 141.033,
      poster_path: "/sIi1efc3FJvunsf4BoGgQ1ycB7S.jpg",
      release_date: "2023-02-09",
      title: "원 웨이",
      video: false,
      vote_average: 6.6,
      vote_count: 82,
    },
    {
      adult: false,
      backdrop_path: "/qAatLCuRhvLyNJbH5IGmxLyU3tx.jpg",
      genre_ids: [16, 14, 12],
      id: 876792,
      original_language: "ja",
      original_title: "劇場版 転生したらスライムだった件 紅蓮の絆編",
      overview:
        "[템페스트]의 서쪽에 위치한 [라자 소아국]. 한때는 금 채굴로 번영했지만 지금은 번영의 그림자는 찾아볼 수조차 없고, 호수는 광산의 독에 오염되어 나라는 위기 상황에 처했다. 여왕 '토와'는 왕가에 대대로 전해 오는 왕관의 마력을 사용해 독을 제거하며 백성을 지키고 있었지만, 그 대가로 왕관에 걸려 있던 저주가 온몸에 퍼져 수명이 단축되고 있었다. 그러던 중, 템페스트에 갑자기 나타난 오거의 생존자 '히이로'. 베니마루 일행의 형님뻘이었다는 히이로는, 토와의 도움으로 살아남았던 것이었다. 자신을 구해 준 토와와 [라자 소아국]을 지키기 위해, 템페스트의 리무루에게 도움을 청하기 위해 온 히이로는 베니마루와 운명의 재회를 한다. 라자를 위기에서 구하기 위해, 그리고 토와에게 걸린 저주의 수수께끼를 풀기 위해, 리무루는 라자로 향하는데...... 그곳에는 놀라운 음모가 기다리고 있었다!",
      popularity: 144.832,
      poster_path: "/kHeX34lOrTM793hCiCS72cIYY6i.jpg",
      release_date: "2023-02-02",
      title: "극장판 전생했더니 슬라임이었던 건에 대하여: 홍련의 인연편",
      video: false,
      vote_average: 7.1,
      vote_count: 29,
    },
    {
      adult: false,
      backdrop_path: "/fjgKMNFo6uj7znrWwTbLzNBVzIT.jpg",
      genre_ids: [27, 9648],
      id: 477462,
      original_language: "en",
      original_title: "The Twin",
      overview:
        "쌍둥이 아들을 잃은 레이첼 가족을 향해 위로를 가장한 이교 집단의 손길이 뻗친다.",
      popularity: 87.66,
      poster_path: "/obJRpZOfC4ul5dr7JIZHsvDyllf.jpg",
      release_date: "2023-02-08",
      title: "트윈",
      video: false,
      vote_average: 6,
      vote_count: 139,
    },
    {
      adult: false,
      backdrop_path: "/84XcRwKHAw4VXdKOYTSW5ARxFEt.jpg",
      genre_ids: [18, 10402],
      id: 817758,
      original_language: "en",
      original_title: "TÁR",
      overview:
        "무대를 장악하는 마에스트로, 욕망을 불태우는 괴물, 베를린 필하모닉 최초의 여성 지휘자 리디아 타르.",
      popularity: 67.556,
      poster_path: "/nSoWzlHD31JjRhkgR1QVPjZzAnk.jpg",
      release_date: "2023-02-22",
      title: "타르",
      video: false,
      vote_average: 7.3,
      vote_count: 372,
    },
    {
      adult: false,
      backdrop_path: "/hhICjHximfBciqxX09d91GgghV8.jpg",
      genre_ids: [18],
      id: 965150,
      original_language: "en",
      original_title: "Aftersun",
      overview:
        "평범한 10대 소녀인 소피는 그동안 자신에게 소홀했던 아버지와 단둘이 튀르키예로 여행을 떠난다. 아버지와 처음으로 둘만의 오붓한 시간을 즐기는 동안, 소피는 어떻게든 자신을 즐겁게 해주려는 아버지의 새로운 이면을 보게 되는데…",
      popularity: 60.132,
      poster_path: "/zZh6x7aHtSxsIQCewZVKEykVNtO.jpg",
      release_date: "2023-02-01",
      title: "애프터썬",
      video: false,
      vote_average: 7.8,
      vote_count: 388,
    },
    {
      adult: false,
      backdrop_path: "/nYla7faWqM3nLCY9arQH1DwXC84.jpg",
      genre_ids: [16, 12, 10751],
      id: 576925,
      original_language: "ru",
      original_title: "Бука. Моё любимое чудище",
      overview:
        "용감하게 세상을 구하는 ‘에드워드’ 왕자와 비밀스럽게 사랑을 키워 나가는 공주 ‘바바라’. 교활한 ‘조이스’의 계략으로 아버지인 왕이 ‘조이스’와 결혼을 시키려 하자 왕궁에서 가까스로 탈출한 ‘바바라’는 숲에서 길을 잃고 험상궂은 몬스터 ‘보기’와 말하는 토끼 ‘버니’를 만나게 된다.  ‘조이스’는 군대를 이끌고 숲으로 향하고 ‘바바라’는 둘의 도움으로 마침내 꿈에 그리던 ‘에드워드’ 왕자를 만나러 찾아가는데… 꿈에도 그리던 ‘에드워드’ 왕자의 진짜 정체는 과연 무엇?  세상을 지배할 수 있는 마법의 물을 훔치려는 ‘조이스’의 음모에 맞서 ‘바바라’는 숲과 왕국을 지켜내고 자신만의 진짜 왕자님을 찾아낼 수 있을까?!",
      popularity: 66.752,
      poster_path: "/wAYAli1axxe3FfRensBZmXkMVtm.jpg",
      release_date: "2023-02-22",
      title: "미녀와 야수: 마법에 걸린 왕자",
      video: false,
      vote_average: 6.5,
      vote_count: 28,
    },
    {
      adult: false,
      backdrop_path: "/33qGtN2GpGEb94pn25PDPeWQZLk.jpg",
      genre_ids: [28],
      id: 894169,
      original_language: "en",
      original_title: "Vendetta",
      overview:
        "딸과 함께 평온한 일상을 보내고 있던 '윌리엄 던컨'.  그러나 의문의 범죄 집단에 의해 딸이 잔혹하게 살해되는 사건이 발생하고, 그녀를 죽인 범인 '대니'는 가벼운 형만을 선고받는다.  결국 자신의 손으로 직접 딸의 복수를 결심한 '던컨'은 '대니'를 살해하지만, 이는 그가 속한 범죄 집단과의 전면전을 알리는 계기가 되어 끝도 없는 전쟁의 서막이 열리는데...",
      popularity: 56.186,
      poster_path: "/uf3HYK3VdcXqH7wZVqQK58U0mO3.jpg",
      release_date: "2023-01-20",
      title: "벤데타: 복수의 시간",
      video: false,
      vote_average: 6.3,
      vote_count: 201,
    },
    {
      adult: false,
      backdrop_path: "/dhfU1d6V25BGEHDAoPrERQFmsl2.jpg",
      genre_ids: [53, 9648, 18],
      id: 768362,
      original_language: "en",
      original_title: "Missing",
      overview:
        "여행을 끝내고 월요일 귀국을 알린 엄마의 영상통화 그리고 마중 나간 딸. 그러나 엄마가 사라졌다  경찰에 도움을 요청하지만, 결정적인 단서들이 나오지 않는 가운데 딸 ‘준’은 엄마의 흔적을 찾기 위해 엄마가 방문한 호텔의 CCTV, 같이 간 지인의 SNS,  거리뷰 지도까지 온라인에 남아있는 모든 흔적을 검색하는데…",
      popularity: 49.257,
      poster_path: "/hxnIi3LCGOdp5H1TbT6YbesfJo2.jpg",
      release_date: "2023-02-22",
      title: "서치 2",
      video: false,
      vote_average: 7.4,
      vote_count: 23,
    },
    {
      adult: false,
      backdrop_path: "/70aVSo3fuZ94jyQ3rT64afEf8lV.jpg",
      genre_ids: [16, 12, 35, 10751, 14],
      id: 676710,
      original_language: "en",
      original_title: "The Amazing Maurice",
      overview:
        "신기한 능력으로 성공적인 사기 행각을 이어가던 모리스와 친구들! 4차원 소녀 ‘멜리시아’에게 정체가 탄로나 어쩔 수 없이 그녀를 도와 마을에 숨겨진 비밀을 찾아 나선 그들은 세상을 지배하려는 절대악 ‘쥐마왕’의 음모를 알아채지만 뜻하지 않은 위험에 처한다. 가까스로 잡혀있던 ‘복숭아’를 구해낸 모리스와 친구들은 마을에서 탈출을 시도하고, 멜리시아는 허당 피리꾼 ‘키이스’와 함께 쥐마왕에게 맞서기 위해 진짜 마술피리를 찾아나서는데..  쥐마왕의 정체는 과연 무엇? 그리고 모리스와 친구들은 무사히 마을에서 벗어날 수 있을 것인가?!",
      popularity: 28.837,
      poster_path: "/m4gi3r7JizAaURreUqjCk306vxz.jpg",
      release_date: "2023-02-15",
      title: "어메이징 모리스",
      video: false,
      vote_average: 6.3,
      vote_count: 27,
    },
    {
      adult: false,
      backdrop_path: "/dp4jcu2tlAyJnJNnCyHXnWnqhUl.jpg",
      genre_ids: [80, 18, 53],
      id: 889699,
      original_language: "fa",
      original_title: "عنکبوت مقدس",
      overview:
        "‘순교자의 땅’이라는 뜻을 가진 이란 최대의 종교도시, 마슈하드 그곳에서 1년 사이 16명의 여성을 살해한 연쇄 살인마 ‘거미’는 자신의 범행과 시체 유기 장소를 직접 언론에 제보하는 대담한 행동을 이어간다. 살인마의 행동에 정당성을 부여하는 여론이 일고 정부와 경찰마저 적극적으로 수사하지 않는 가운데 여성 저널리스트 ‘라히미’만이 홀로 살인마의 실체를 밝히기 위해 그의 뒤를 쫓는데…",
      popularity: 23.254,
      poster_path: "/bdaUrseeOHSaChDSaRypa11T3YZ.jpg",
      release_date: "2023-02-08",
      title: "성스러운 거미",
      video: false,
      vote_average: 7.3,
      vote_count: 102,
    },
    {
      adult: false,
      backdrop_path: "/wPJKyDq1F9b4VtpF9dz8FPKVuS5.jpg",
      genre_ids: [9648, 10749, 878, 14],
      id: 804725,
      original_language: "zh",
      original_title: "想見你",
      overview:
        "세상을 떠난 남자친구 왕취안성을 잊지 못한 황위쉬안이 운명처럼 1998년으로 타임슬립해 그와 똑 닮은 남학생 리쯔웨이를 만나 벌어지는 아시아 메가 히트 타임슬립 로맨스",
      popularity: 18.337,
      poster_path: "/fsOBfobu5PificuDpVoKUKjafi5.jpg",
      release_date: "2023-01-25",
      title: "상견니",
      video: false,
      vote_average: 5.6,
      vote_count: 7,
    },
  ],
  total_pages: 4,
  total_results: 65,
};
